/*
Cashfree Payout APIs

Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

API version: 2024-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_payout

import (
	"encoding/json"
	"strings"
)

// checks if the CreateTransferResponseBeneficiaryDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTransferResponseBeneficiaryDetails{}

// CreateTransferResponseBeneficiaryDetails It displays the details of the beneficiary.
type CreateTransferResponseBeneficiaryDetails struct {
	// It displays the unique ID to identify the beneficiary to whom you initiated the transfer request.
	BeneficiaryId *string `json:"beneficiary_id,omitempty"`
	BeneficiaryInstrumentDetails *CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails `json:"beneficiary_instrument_details,omitempty"`
}


func (o CreateTransferResponseBeneficiaryDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTransferResponseBeneficiaryDetails) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BeneficiaryId) {
		toSerialize["beneficiary_id"] = o.BeneficiaryId
	}
	if !IsNil(o.BeneficiaryInstrumentDetails) {
		toSerialize["beneficiary_instrument_details"] = o.BeneficiaryInstrumentDetails
	}
	return toSerialize, nil
}



