/*
Cashfree Payout APIs

Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

API version: 2024-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_payout

import (
	"encoding/json"
	"strings"
)

// checks if the FetchBatchTransferResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FetchBatchTransferResponse{}

// FetchBatchTransferResponse Batch Transfer Status V2 Response
type FetchBatchTransferResponse struct {
	// It displays the unique ID you created to identify the batch transfer.
	BatchTransferId *string `json:"batch_transfer_id,omitempty"`
	// It displays the unique ID created by Cashfree Payments. You receive this ID in the response after initiating the batch transfer request.
	CfBatchTransferId *string `json:"cf_batch_transfer_id,omitempty"`
	// It displays the status of the batch transfer.
	Status *string `json:"status,omitempty"`
	Transfers []CreateTransferResponse `json:"transfers,omitempty"`
}


func (o FetchBatchTransferResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FetchBatchTransferResponse) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BatchTransferId) {
		toSerialize["batch_transfer_id"] = o.BatchTransferId
	}
	if !IsNil(o.CfBatchTransferId) {
		toSerialize["cf_batch_transfer_id"] = o.CfBatchTransferId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Transfers) {
		toSerialize["transfers"] = o.Transfers
	}
	return toSerialize, nil
}



