/*
Cashfree Payout APIs

Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

API version: 2024-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_payout

import (
	"encoding/json"
	"strings"
)

// checks if the CreateBatchTransferRequestTransfersInnerBeneficiaryDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBatchTransferRequestTransfersInnerBeneficiaryDetails{}

// CreateBatchTransferRequestTransfersInnerBeneficiaryDetails It should contain the details of the beneficiary who receives the transfer amount.
type CreateBatchTransferRequestTransfersInnerBeneficiaryDetails struct {
	// It is the unique ID you created to identify the beneficiary. Alphanumeric characters are allowed.
	BeneficiaryId *string `json:"beneficiary_id,omitempty"`
	// It is the name of the beneficiary. The maximum character limit is 100.
	BeneficiaryName *string `json:"beneficiary_name,omitempty"`
	BeneficiaryInstrumentDetails *CreateBatchTransferRequestTransfersInnerBeneficiaryDetailsBeneficiaryInstrumentDetails `json:"beneficiary_instrument_details,omitempty"`
	BeneficiaryContactDetails *CreateTransferRequestBeneficiaryDetailsBeneficiaryContactDetails `json:"beneficiary_contact_details,omitempty"`
}


func (o CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBatchTransferRequestTransfersInnerBeneficiaryDetails) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BeneficiaryId) {
		toSerialize["beneficiary_id"] = o.BeneficiaryId
	}
	if !IsNil(o.BeneficiaryName) {
		toSerialize["beneficiary_name"] = o.BeneficiaryName
	}
	if !IsNil(o.BeneficiaryInstrumentDetails) {
		toSerialize["beneficiary_instrument_details"] = o.BeneficiaryInstrumentDetails
	}
	if !IsNil(o.BeneficiaryContactDetails) {
		toSerialize["beneficiary_contact_details"] = o.BeneficiaryContactDetails
	}
	return toSerialize, nil
}



