/*
Cashfree Payout APIs

Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

API version: 2024-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_payout

import (
	"encoding/json"
	"strings"
)

// checks if the CreateBeneficiaryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBeneficiaryRequest{}

// CreateBeneficiaryRequest Find the request parameters to create a beneficiary
type CreateBeneficiaryRequest struct {
	// It is the unique ID you create to identify the beneficiary. Alphanumeric, underscore ( _ ), pipe ( | ), and dot ( . ) are allowed.
	BeneficiaryId string `json:"beneficiary_id"`
	// It is the name of the beneficiary. The maximum character limit is 100. Only alphabets and whitespaces are allowed.
	BeneficaryName string `json:"beneficary_name"`
	BeneficiaryInstrumentDetails *CreateBeneficiaryRequestBeneficiaryInstrumentDetails `json:"beneficiary_instrument_details,omitempty"`
	BeneficiaryContactDetails *CreateBeneficiaryRequestBeneficiaryContactDetails `json:"beneficiary_contact_details,omitempty"`
}


func (o CreateBeneficiaryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBeneficiaryRequest) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	toSerialize["beneficiary_id"] = o.BeneficiaryId
	toSerialize["beneficary_name"] = o.BeneficaryName
	if !IsNil(o.BeneficiaryInstrumentDetails) {
		toSerialize["beneficiary_instrument_details"] = o.BeneficiaryInstrumentDetails
	}
	if !IsNil(o.BeneficiaryContactDetails) {
		toSerialize["beneficiary_contact_details"] = o.BeneficiaryContactDetails
	}
	return toSerialize, nil
}



