/*
Cashfree Payout APIs

Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

API version: 2024-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_payout

import (
	"encoding/json"
	"strings"
)

// checks if the BeneficiaryBeneficiaryInstrumentDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BeneficiaryBeneficiaryInstrumentDetails{}

// BeneficiaryBeneficiaryInstrumentDetails It displays the payment instrument details of the beneficiary.
type BeneficiaryBeneficiaryInstrumentDetails struct {
	// It displays the bank account of the beneficiary.]
	BankAccountNumber *string `json:"bank_account_number,omitempty"`
	// It displays the IFSC information of the beneficiary's bank account.
	BankIfsc *string `json:"bank_ifsc,omitempty"`
	// It displays the UPI VPA information of the beneficiary.
	Vpa *string `json:"vpa,omitempty"`
}


func (o BeneficiaryBeneficiaryInstrumentDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BeneficiaryBeneficiaryInstrumentDetails) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BankAccountNumber) {
		toSerialize["bank_account_number"] = o.BankAccountNumber
	}
	if !IsNil(o.BankIfsc) {
		toSerialize["bank_ifsc"] = o.BankIfsc
	}
	if !IsNil(o.Vpa) {
		toSerialize["vpa"] = o.Vpa
	}
	return toSerialize, nil
}



