/*
Cashfree Payout APIs

Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

API version: 2024-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_payout

import (
	"encoding/json"
	"strings"
)

// checks if the CreateBatchTransferRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBatchTransferRequest{}

// CreateBatchTransferRequest Batch Transfer V2
type CreateBatchTransferRequest struct {
	// It is the unique ID you create to identify the batch transfer request. The maximum character limit is 60. Alphanumeric and underscore ( _ ) characters are allowed.
	BatchTransferId string `json:"batch_transfer_id"`
	Transfers []CreateBatchTransferRequestTransfersInner `json:"transfers,omitempty"`
}


func (o CreateBatchTransferRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBatchTransferRequest) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	toSerialize["batch_transfer_id"] = o.BatchTransferId
	if !IsNil(o.Transfers) {
		toSerialize["transfers"] = o.Transfers
	}
	return toSerialize, nil
}



