/*
Cashfree Payout APIs

Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.

API version: 2024-01-01
Contact: developers@cashfree.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cashfree_payout

import (
	"encoding/json"
	"strings"
)

// checks if the CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetailsCardDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetailsCardDetails{}

// CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetailsCardDetails It should contain the card details of the beneficiary.
type CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetailsCardDetails struct {
	// It is the tokenised card number or card token for this transfer.
	CardToken *string `json:"card_token,omitempty"`
	// It is the network type of the card - VISA/MASTERCARD.
	CardNetworkType *string `json:"card_network_type,omitempty"`
	// It is the formatted chip/cryptogram data relating to the token cryptogram. The maximum character limit is 600. It is optional for MASTERCARD and not required for VISA.
	CardCryptogram *string `json:"card_cryptogram,omitempty"`
	// It is applicable only for MASTERCARD. The format for the valid token expiry date should be YYYY-MM. It cannot be null. Provide a valid tokenExpiry if collected from the customers. If unavailable, populate a static value with a forward year and month in the correct format (YYYY-MM). The maximum character limit is 10.
	CardTokenExpiry *string `json:"card_token_expiry,omitempty"`
	// It is the type of the card. DEBIT and CREDIT are the only values allowed. The default value is CREDIT if the parameter does not exist or not specified.
	CardType *string `json:"card_type,omitempty"`
	// A maximum of 3 alphanumeric characters are allowed. It is an optional parameter for MASTERCARD.
	CardTokenPANSequenceNumber *string `json:"card_token_PAN_sequence_number,omitempty"`
}


func (o CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetailsCardDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTransferRequestBeneficiaryDetailsBeneficiaryInstrumentDetailsCardDetails) ToMap() (map[string]interface{}, error) {
	strings.HasPrefix("cf", "cf")
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CardToken) {
		toSerialize["card_token"] = o.CardToken
	}
	if !IsNil(o.CardNetworkType) {
		toSerialize["card_network_type"] = o.CardNetworkType
	}
	if !IsNil(o.CardCryptogram) {
		toSerialize["card_cryptogram"] = o.CardCryptogram
	}
	if !IsNil(o.CardTokenExpiry) {
		toSerialize["card_token_expiry"] = o.CardTokenExpiry
	}
	if !IsNil(o.CardType) {
		toSerialize["card_type"] = o.CardType
	}
	if !IsNil(o.CardTokenPANSequenceNumber) {
		toSerialize["card_token_PAN_sequence_number"] = o.CardTokenPANSequenceNumber
	}
	return toSerialize, nil
}



